/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gvillena;

import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.ListModel;

/**
 *
 * @author alumno
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMovistar = new javax.swing.JToggleButton();
        btnClaro = new javax.swing.JToggleButton();
        pblEquiposMovilles = new javax.swing.JScrollPane();
        lstEquiposMoviles = new javax.swing.JList();
        lblTEquiposMoviles = new javax.swing.JLabel();
        lblTCaracteristicas = new javax.swing.JLabel();
        lblPantalla = new javax.swing.JLabel();
        lblCamara = new javax.swing.JLabel();
        lblProcesador = new javax.swing.JLabel();
        lblTPantalla = new javax.swing.JLabel();
        lblTCamara = new javax.swing.JLabel();
        lblTProcesador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnMovistar.setText("MOVISTAR");
        btnMovistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovistarActionPerformed(evt);
            }
        });

        btnClaro.setText("CLARO");
        btnClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaroActionPerformed(evt);
            }
        });

        lstEquiposMoviles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "123", "456", "789", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstEquiposMoviles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEquiposMovilesValueChanged(evt);
            }
        });
        pblEquiposMovilles.setViewportView(lstEquiposMoviles);

        lblTEquiposMoviles.setText("EQUIPOS MOVILES");

        lblTCaracteristicas.setText("CARACTERISTICAS ");

        lblPantalla.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblPantalla.setText("4.3\"");

        lblCamara.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblCamara.setText("8MP");

        lblProcesador.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblProcesador.setText("1.3GHz");

        lblTPantalla.setText("PANTALLA");

        lblTCamara.setText("CAMARA");

        lblTProcesador.setText("PROCESADOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pblEquiposMovilles, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPantalla)
                            .addComponent(lblTPantalla))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(lblCamara)
                                .addGap(40, 40, 40)
                                .addComponent(lblProcesador)
                                .addGap(0, 67, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblTCamara)
                                .addGap(78, 78, 78)
                                .addComponent(lblTProcesador)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnMovistar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblTEquiposMoviles)
                                .addGap(193, 193, 193)
                                .addComponent(lblTCaracteristicas)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClaro, btnMovistar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMovistar)
                            .addComponent(btnClaro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTEquiposMoviles)
                            .addComponent(lblTCaracteristicas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pblEquiposMovilles, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTPantalla)
                            .addComponent(lblTCamara)
                            .addComponent(lblTProcesador))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPantalla)
                            .addComponent(lblCamara)
                            .addComponent(lblProcesador))
                        .addGap(69, 69, 69)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
   
        lblPantalla.setText("9.8");
        lblCamara.setText("8MP");
        lblProcesador.setText("1.5Gz");
    }//GEN-LAST:event_formWindowOpened

    private void btnMovistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovistarActionPerformed
        System.out.println("CLICK MOVISTAR");        
        btnClaro.setSelected(false);
        lblPantalla.setText("--");
        lblCamara.setText("--");
        lblProcesador.setText("--");
        
        ListModel<String> modelMovistar = new AbstractListModel<String>() {            
            String[] strings = { "MVSTR 01", "MVSTR 02", "MVSTR 03"};            
            
            @Override
            public int getSize() { return strings.length; }

            @Override
            public String getElementAt(int index) { return strings[index]; }
        };
        
        lstEquiposMoviles.setModel(modelMovistar);
    }//GEN-LAST:event_btnMovistarActionPerformed

    private void btnClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaroActionPerformed
        System.out.println("CLICK CLARO");
        btnMovistar.setSelected(false);
        lblPantalla.setText("--");
        lblCamara.setText("--");
        lblProcesador.setText("--");
        ListModel<String> modelClaro = new AbstractListModel<String>() {            
            String[] strings = { "CLARO 01", "CLARO 02", "CLARO 03"};            
            
            @Override
            public int getSize() { return strings.length; }

            @Override
            public String getElementAt(int index) { return strings[index]; }
        };
        lstEquiposMoviles.setModel(modelClaro);
    }//GEN-LAST:event_btnClaroActionPerformed

    private void lstEquiposMovilesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEquiposMovilesValueChanged
        if (!evt.getValueIsAdjusting()) {
            if (btnClaro.isSelected()) {
                switch (lstEquiposMoviles.getSelectedIndex()) {
                    case 0:
                        System.out.println("CLARO 0");
                        lblPantalla.setText("4.3\"");
                        lblCamara.setText("6MP");
                        lblProcesador.setText("1.3GHz");                                                
                        break;
                    case 1:
                        System.out.println("CLARO 1");
                        lblPantalla.setText("6.2\"");
                        lblCamara.setText("8MP");
                        lblProcesador.setText("2.3GHz");                                                
                        break;
                    case 2:
                        System.out.println("CLARO 2");
                        lblPantalla.setText("7.3\"");
                        lblCamara.setText("10MP");
                        lblProcesador.setText("2.7GHz");                                                
                        break;                    
                }
            }
            else if (btnMovistar.isSelected())
            {
                switch (lstEquiposMoviles.getSelectedIndex()) {
                    case 0:
                        System.out.println("MOVISTAR 0");
                        lblPantalla.setText("6.3\"");
                        lblCamara.setText("5MP");
                        lblProcesador.setText("1.7GHz");                                                
                        break;
                    case 1:
                        System.out.println("MOVISTAR 1");
                        lblPantalla.setText("4.3\"");
                        lblCamara.setText("4MP");
                        lblProcesador.setText("2.2GHz");                                                
                        break;
                    case 2:
                        System.out.println("MOVISTAR 2");
                        lblPantalla.setText("5.1\"");
                        lblCamara.setText("7MP");
                        lblProcesador.setText("1.2GHz");                                                
                        break;                    
                }
            }
        }
        
        
    }//GEN-LAST:event_lstEquiposMovilesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnClaro;
    private javax.swing.JToggleButton btnMovistar;
    private javax.swing.JLabel lblCamara;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblProcesador;
    private javax.swing.JLabel lblTCamara;
    private javax.swing.JLabel lblTCaracteristicas;
    private javax.swing.JLabel lblTEquiposMoviles;
    private javax.swing.JLabel lblTPantalla;
    private javax.swing.JLabel lblTProcesador;
    private javax.swing.JList lstEquiposMoviles;
    private javax.swing.JScrollPane pblEquiposMovilles;
    // End of variables declaration//GEN-END:variables
}
